apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emp-service
  name: emp-service
  namespace: default
  
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emp-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
       labels:
        app: emp-service
    spec:
      containers:
      - image: isumala/emp-service:1.0
        imagePullPolicy: IfNotPresent
        name: emp-service
       
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: emp-service
  name: emp-service
  namespace: default
  
spec:
  
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: emp-service
  sessionAffinity: None
  type: NodePort
